# Generated by Django 4.2.6 on 2023-11-15 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
