# Generated by Django 4.2.6 on 2023-11-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_asignatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='profersor',
            new_name='profesor',
        ),
    ]
