# Generated by Django 4.2.6 on 2023-11-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_profersor_asignatura_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asignatura',
            field=models.CharField(default='nn', max_length=50),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='seccion',
            field=models.CharField(default='nn', max_length=5),
        ),
    ]
